### ISSUE TITLE
Compilation error with Java8

### ISSUE THREAD

**Issue by mhjort** [jimpil/duratom#15]
I get this error with Java 8. I guess the DirectByteArrayOutputStream Java class has been compiled with Java8.

```
Syntax error macroexpanding at (utils.clj:1:1).
Execution error (UnsupportedClassVersionError) at java.lang.ClassLoader/defineClass1 (ClassLoader.java:-2).
dbaos/DirectByteArrayOutputStream has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by jimpil** [comment]
OMG! I'm working on the another project that requires Java 9, and I must have forgotten to  switch JDKs before releasing :(

I do apologise - I'll cut a new release shortly...

**Comment by jimpil** [comment]
Version 0.4.5 will hit clojars any minute now, and all the Java source has been compiled with Java-8. Again, apologies for the inconvenience.

**Comment by jjttjj** [comment]
I seem to still be getting a similar error with duratom 0.4.5 when requiring `duratom` on openjdk 12.0.2

```
Syntax error (UnsupportedClassVersionError) compiling at (duratom/utils.clj:1:1).
dbaos/DirectByteArrayOutputStream has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0

```

**Comment by jimpil** [comment]
Wait what? 12.0.2 was the version I used (accidentally) when i released duratom 0.4.4 and caused the original problem. Version 0.4.5 was compiled with Java8 - I'm pretty sure about that...are you sure you don't have any ghost class files lying around (i.e. have you trying cleaning and re-compiling everything)?

**Comment by jjttjj** [comment]
Strange, it does seem to be happening to me with a minimal project (just deps.edn depending on clojure and duratom 0.4.5 and a single source file requiring duratom), after deleting all local duratom jars in `.m2`.  I will try to dig deeper into thise later

**Comment by jimpil** [comment]
Are you sure you're on jdk 12? If so, that error message either doen't make much sense, or I'm reading it completely wrong! I am open to the possibility that I messed things up in 0.4.5, but I don't see how you can possibly get that error :(. I can only see that error happening if you're still on 8, and I somehow compiled 0.4.5 with 12 (which was the original issue) - right?

**Comment by jjttjj** [comment]
You're right, sorry! 
Somehow Cider is using Java 1.8, despite having only installed jdk 12 on a fresh linux install, and  version 12 is coming up most places for my `$ java -version`. Sorry again for the confusion.
