### ISSUE TITLE
New (to me) compile warning

### ISSUE THREAD

**Issue by harold** [jimpil/duratom#20]
This morning I started seeing this:

```
WARNING: identity already refers to: #'clojure.core/identity in namespace: duratom.utils, being replaced by: #'duratom.utils/identity
```
Guessing it's caused by this line:
https://github.com/jimpil/duratom/blob/d481707e8a5dee342133b2eea25fc86f2be2a2b6/src/clojure/duratom/utils.clj#L152

So maybe these:
https://github.com/jimpil/duratom/blob/fc630c96d0f3125c6dd85120fda094093ddec6a6/src/clojure/duratom/core.clj#L55
https://github.com/jimpil/duratom/blob/fc630c96d0f3125c6dd85120fda094093ddec6a6/src/clojure/duratom/core.clj#L67

Could instead say:
```
(juxt #(first %&) f)
```

:smile: 

Hope you're well. As ever, thanks for duratom, we still have zillions of nippy duratoms with gigabytes of stuff in them and we love it.

**Comment by harold** [comment]
Or, I guess maybe `(:refer-clojure :exclude [identity])` in utils.

**Comment by jimpil** [comment]
Hi there,

Your message found me on my second day of holidays, hence the late reply...
This is not really a major (or even minor) issue, but I can see how it can be somewhat annoying. I will `:refer-exclude` (per your suggestion) in the next release (sometime this week I hope).

By the way, duratoms can now be distributed - see [hazel-atom](https://github.com/jimpil/hazel-atom). I can help you set that up if you need to. Alternatively, you can see an example [here](https://github.com/jimpil/circlecast#persistence).

Hope that helps ;)
Kind regards

**Comment by harold** [comment]
😄 No worries on late reply, and yes, this is indeed minor, so no rush on the fix.

Glad you're around and still interested. I say it every time, but we love this library and use it literally 24hrs a day to store so so so much stuff.

Thank you!

PS. distributed sounds like an interesting direction. I'll keep my brain open to opportunities to use that. Thank you again.

**Comment by jellelicht** [comment]
Any prognosis when 0.5.3 is going to be released? You can't put a price on a CI pipeline that passes without warnings :wink:

**Comment by jimpil** [comment]
Hi guys,

Apologies for the wait - 0.5.3 is out and it contains a single change (the addition of a `:refer-exclude` clause in utils.clj). 

Cheers :+1:

**Comment by harold** [comment]
Great! Thank you.

Can you push this commit: https://github.com/jimpil/duratom/commit/8cfc7d9d889d4e7fada72bb3315d890296d6de3f

Linked from here: https://clojars.org/duratom

You're the best.

**Comment by jimpil** [comment]
Done :+1:

**Comment by harold** [comment]
Very very cool. Thank you. Stay rad.
