### ISSUE TITLE
pr-str is affected by *print-length*

### ISSUE THREAD

**Issue by AdamClements** [jimpil/duratom#5]
If the user has *print-length* set then any lengthy lists etc will get cut off with [1 2 3 ...] which not only loses the data but isn't valid edn and won't read back in. Need to wrap calls to pr-str with `(binding [*print-length* nil] (pr-str whatever))`

**Comment by harold** [comment]
This is an interesting point. Did you have `*print-length*` set in a context where a duratom was written?

**Comment by AdamClements** [comment]
I was evaluating the code in Emacs, where my repl defaults limit the print length to stop accidentally spewing too much out at the repl. I think that's a fairly common set up

**Comment by harold** [comment]
Yup. Makes sense. Good catch.

**Comment by jimpil** [comment]
Good catch indeed and thanks for reporting it - I will address it in the next release which should be this weekend. 

Kind regards

**Comment by jimpil** [comment]
`duratom 0.3.8` has been released and fixes this. Thanks again for reporting it...:)
