### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by harold** [jimpil/duratom#9]
Hi! I hope you're well. I still use this library every day and it is great!

I noticed the version is up to `"0.4.1"`, and I haven't upgraded in a while. What are the recent changes? Are they things I'll want to upgrade for? Have there been any breaking api changes?

I poked around the CHANGELOG.md, but it looks like the default `lein` template one.

Regardless, thanks again.

**Comment by jimpil** [comment]
Hi Harold,

I'm glad you're finding `duratom` useful. Unfortunately, there is not enough time in the day to maintain detailed logs for all my projects. A quick skim through the commits reveals that the last two releases have primarily changes relating to S3-backed storage. Therefore, if you're not doing anything relating to S3, then there is no need for you to update. On the other hand, you can always try the latest, and see it anything breaks for you. 

Kind regards

**Comment by harold** [comment]
Thanks for the reply. I totally understand. I wish you the best in all endeavors.
